#!/usr/bin/env bash
#
# function to handle SIGTERM signal
function handle_sigterm {
    echo "I am invincible!!!"
}

# trap SIGTERM signal and call the handle_sigterm function
trap handle_sigterm SIGTERM

# infinite loop
while true
do
    echo "To infinity and beyond"
    sleep 2
done