#!/usr/bin/env bash
# This script is displaying "Best School" 10 times using while
n="Best School"
i=1

while [ $i -le 10 ];
do
    if [ $i == 9 ]; then
        echo "Hi"
    else
        echo "$n"
    fi
    ((i++))
done