#!/usr/bin/env bash
# This script is displaying goodluck (at 8) or badluck (at 4)
n="Best School"
i=1

while [ $i -le 10 ];
do
    if [ $i == 4 ]; then
        echo "bad luck"
    elif [ $i == 8 ]; then
        echo "good luck"
    else
        echo "$n"
    fi
    ((i++))
done