#!/usr/bin/env bash
# This script is displaying goodluck (at 8) or badluck (at 4)
i=1

while [ $i -le 20 ];
do
    echo "$i"
    case $i in
      4)
       echo "bad luck from China"
       ;;
      9)
       echo "bad luck from Japan"
       ;;
     17)
       echo "bad luck from Italy"
       ;;
    esac
    ((i++))
done
